#include "Global.h"

float SPECULAR_LIGTHING_FACTOR = 0.5;
float INCIDENT_LIGTHING_FACTOR = 0.3;
float PROXIMITY_LIGTHING_FACTOR = 0.3;
float AMBIENT_LIGTHING_FACTOR = 0.15;

int MAX_REFLECTIONS = 1;

float SHADOW_BIAS = 0.0001; 
